---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.20.0"
docker_compose_path: /usr/local/bin/docker-compose

# Docker Daemon options.
docker_daemon_options:

# Docker proxy options.
docker_use_proxy: false
docker_http_proxy: ""
docker_https_proxy: ""

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# Used only for RedHat/CentOS.
docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

# User to add in docker group
docker_users: []
docker_reset_ssh: false

